version: "2.4"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - biblio-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - biblio-network

  db_user:
    image: mysql:8.0
    container_name: db_user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_user
    ports:
      - "3306:3306"
    networks:
      - biblio-network

  db_book:
    image: mysql:8.0
    container_name: db_book
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_book
    ports:
      - "3307:3306"
    networks:
      - biblio-network

  db_emprunter:
    image: mysql:8.0
    container_name: db_emprunter
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_emprunter
    ports:
      - "3308:3306"
    networks:
      - biblio-network

  eureka-server:
    build: ./eurika
    container_name: eureka-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-server
    networks:
      - biblio-network

  gateway-service:
    build: ./gateway
    container_name: gateway-service
    ports:
      - "9999:9999"
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=gateway-service

      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network

  user-service:
    build: ./user
    container_name: user-service
    depends_on:
      - eureka-server
      - db_user
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network

  book-service:
    build: ./book
    container_name: book-service
    depends_on:
      - eureka-server
      - db_book
    environment:
      - SPRING_APPLICATION_NAME=book-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network

  emprunt-service:
    build: ./emprunter
    container_name: emprunt-service
    depends_on:
      - eureka-server
      - user-service
      - book-service
      - db_emprunter
      - kafka
    environment:
      - SPRING_APPLICATION_NAME=emprunt-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network

  notification-service:
    build: ./notification
    container_name: notification-service
    depends_on:
      - eureka-server
      - kafka
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network

networks:
  biblio-network:
    driver: bridge
